# Generated by Django 3.0.8 on 2020-07-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readit_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subreaditmodel',
            name='slug',
        ),
    ]
