# Generated by Django 3.0.8 on 2020-07-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readit_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreaditmodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
    ]
