# Generated by Django 3.0.8 on 2020-07-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readit_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreaditmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
