# Generated by Django 3.0.8 on 2020-07-14 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readit_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='subreadit',
        ),
        migrations.RemoveField(
            model_name='subscriptionmodel',
            name='user',
        ),
        migrations.CreateModel(
            name='CreateSubreaditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
