# Generated by Django 3.0.8 on 2020-07-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readit_site', '0002_subreaditmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreaditmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
